config/routes.rb
Rails.application.routes.draw do

  get 'login/:locale',    :to => 'sessions#new',      :as => 'login'
  get  'logout',   :to => 'sessions#destroy',  :as => 'logout'
  post 'sessions', :to => 'sessions#create',   :as => 'sessions'
  get  'products', :to => 'products#index',    :as => 'products'
  get  'cart',     :to => 'cart_products#index',:as => 'cart'

  scope "(:locale)", :locale => /ja|en/ do
     resources :users
  end

  root 'pages#index'
  get 'userid/:locale',   :to => 'pages#userid', :as => 'userid'
  get 'stores', :to => 'stores#index', :as => 'stores'
  get 'store/:id',  :to => 'stores#show',  :as => 'store'

  get 'coupons', :to => 'coupons#index', :as => 'coupons'
  get 'addtocart/:pid', :to => 'cart_products#add'  , :as=> 'addtocart'
  get 'remove/:id', :to => 'cart_products#remove', :as => 'remove'

end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController

	def index
		query = "
		SELECT salesforce.cartitem__c.id AS cartitem_id, salesforce.cartitem__c.*, salesforce.product__c.*
		FROM salesforce.cartitem__c
		INNER JOIN salesforce.product__c ON salesforce.cartitem__c.product__c = salesforce.product__c.sfid
		WHERE salesforce.cartitem__c.user__c = '#{session['user_id']}'
		";
		#print query
		conn = PG::Connection.open(ENV['DATABASE_URL'])
		@res = conn.exec_params(query)
		conn.close
	end

	def add
		product_id = params[:pid]
		#find product sfid
		conn = PG::Connection.open(ENV['DATABASE_URL'])
		product = conn.exec_params("SELECT sfid FROM salesforce.product__c WHERE id = '#{product_id}'")
		product_sfid = product[0]['sfid']
		
		#insert into cart		
		conn.exec_params("INSERT INTO salesforce.cartitem__c (product__c, user__c, quantity__c) VALUES ('#{product_sfid}','#{session['user_id']}', 1)  ")
        #@res = conn.exec_params("INSERT INTO salesforce.contact (lastname, password__c, email) VALUES ('#{@user.name}','#{@user.password}','#{@user.email}')")
		conn.close

		redirect_to cart_path
	end

	def remove
		id = params[:id]
		conn = PG::Connection.open(ENV['DATABASE_URL'])
		conn.exec_params( "DELETE FROM salesforce.cartitem__c WHERE id = '#{id}'" );
		conn.close		
		redirect_to cart_path
	end

end



#SELECT salesforce.cartitem__c.*, salesforce.product__c.* FROM salesforce.cartitem__c INNER JOIN salesforce.product__c ON salesforce.cartitem__c.product__c = salesforce.product__c.sfid WHERE salesforce.cartitem__c.user__c = '003280000083synAAA'

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/views/cart_products/index.html.erb
<div class="container">
<h3><%= t('your_cart') %></h3>
	<table class="table">
		<tr>
			<th colspan="2"><%= t('product') %></th>
			<th><%= t('unit_price') %></th>
			<th><%= t('quantity') %></th>
			<th></th>
		</tr>
		<% @res.each do |product| %>
			<tr>
				<td><img src="<%=product['image_url__c']%>" style="width:50px;" /></td>
				<td><%=product['name']%></td>
				<td><%=product['price__c']%></td>
				<td><%=product['quantity__c']%></td>
				<td><%=link_to( t('delete'), remove_path(product['cartitem_id']))%></td>
			</tr>
		<% end %>
	</table>

	<div class="text-center">
		<%=link_to t('continue_shopping'), products_path %> &nbsp;&nbsp;&nbsp;
		<button class="btn btn-danger"><%= t('checkout') %></button>
	</div>

</div>