config/routes.rb
Rails.application.routes.draw do

  get 'login/:locale',    :to => 'sessions#new',      :as => 'login'
  get  'logout',   :to => 'sessions#destroy',  :as => 'logout'
  post 'sessions', :to => 'sessions#create',   :as => 'sessions'
  get  'products', :to => 'products#index',    :as => 'products'
  get  'cart',     :to => 'cart_products#index',:as => 'cart'

  scope "(:locale)", :locale => /ja|en/ do
     resources :users
  end

  root 'pages#index'
  get 'userid/:locale',   :to => 'pages#userid', :as => 'userid'
  get 'stores', :to => 'stores#index', :as => 'stores'
  get 'store/:id',  :to => 'stores#show',  :as => 'store'

  get 'coupons', :to => 'coupons#index', :as => 'coupons'
  get 'addtocart/:pid', :to => 'cart_products#add'  , :as=> 'addtocart'
  get 'remove/:id', :to => 'cart_products#remove', :as => 'remove'

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		require 'pg'
		#conn = PG::Connection.open(:dbname => 'myapp_development')
        conn = PG::Connection.open(ENV['DATABASE_URL'])
		@res = conn.exec_params('SELECT * from salesforce.product__c')
		conn.close

	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="container">
	<h3><%= t('product_catalog') %></h3>


	<% @res.each do |product| %>

		<div class="panel panel-default">
			<div class="panel-heading"><%=product['name']%></div>
			<div class="panel-body">
				<div class="row">
					<div class="col-sm-4">
						<img src="<%=product['image_url__c']%>" style="height:200px;"/>
					</div>
					<div class="col-sm-8">
						<%=product['description__c']%>
						<div class="text-right" style="padding-top:10px;">
							<%=link_to t('add_to_cart'),  addtocart_path( product['id'] ), class:"btn btn-success"   %>
						</div>
					</div>
				</div>

			</div>
		</div>



	<% end %>






</div>