config/routes.rb
Rails.application.routes.draw do

  get 'login/:locale',    :to => 'sessions#new',      :as => 'login'
  get  'logout',   :to => 'sessions#destroy',  :as => 'logout'
  post 'sessions', :to => 'sessions#create',   :as => 'sessions'
  get  'products', :to => 'products#index',    :as => 'products'
  get  'cart',     :to => 'cart_products#index',:as => 'cart'

  scope "(:locale)", :locale => /ja|en/ do
     resources :users
  end

  root 'pages#index'
  get 'userid/:locale',   :to => 'pages#userid', :as => 'userid'
  get 'stores', :to => 'stores#index', :as => 'stores'
  get 'store/:id',  :to => 'stores#show',  :as => 'store'

  get 'coupons', :to => 'coupons#index', :as => 'coupons'
  get 'addtocart/:pid', :to => 'cart_products#add'  , :as=> 'addtocart'
  get 'remove/:id', :to => 'cart_products#remove', :as => 'remove'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>NewApp</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>
	<style>
		.navbar-brand {
			background: url(<%= getImageByCode("03") == false ? image_url('logo.png') : getImageByCode("03") %>) no-repeat left center;
			background-size: contain;
			height: 50px;
			width: 250px;
		}
	</style>
</head>
<body>
	<!-- Fixed navbar -->
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/"></a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>
						<%=link_to root_path do%>
						<span class="glyphicon glyphicon-home" aria-hidden="true"></span> <%= t('menu_home') %>
						<% end %>
					</li>
<!--
					<li>
						<%=link_to users_path do%>
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span> ユーザ
						<% end %>
					</li>
-->
					<li>
						<%=link_to products_path do%>
						<span class="glyphicon glyphicon-tag" aria-hidden="true"></span> <%= t('menu_product') %>
						<% end %>
					</li>
					<li>
						<%=link_to cart_path do%>
						<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> <%= t('menu_cart') %>
						<% end %>
					</li>
					<li>
						<%=link_to userid_path do%>
						<span class="glyphicon glyphicon-qrcode" aria-hidden="true"></span> <%= t('menu_mobile_member_card') %>
						<% end %>
					</li>
					<li>
						<%=link_to coupons_path do%>
							<span class="glyphicon glyphicon-gift" aria-hidden="true"></span> <%= t('menu_coupon') %>
							<% if @has_new_coupons %>
								<span class="label label-danger label-as-badge"><%=@num_coupons%></span>
							<% end %>
						<% end %>
					</li>
					<li>
						<%=link_to stores_path do%>
						<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> <%= t('menu_nearby_shops') %>
						<% end %>
					</li>
		<!--
		            <li class="dropdown">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
		              	<span class="glyphicon glyphicon-alert" aria-hidden="true"></span>
		              	Dropdown <span class="caret"></span>
		          	  </a>
		              <ul class="dropdown-menu">
		                <li><a href="#">StarAction</a></li>
		                <li><a href="#">Another action</a></li>
		                <li><a href="#">Something else here</a></li>
		                <li role="separator" class="divider"></li>
		                <li class="dropdown-header">Nav header</li>
		                <li><a href="#">Separated link</a></li>
		                <li><a href="#">One more separated link</a></li>
		              </ul>
		            </li>
		        -->
		        <li>
		        	<%=link_to logout_path do%>
		        	<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> <%= t('menu_logout') %>
		        	<% end %>
		        </li>
		    </ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>

<%= yield %>


<script type="text/javascript">
piAId = '70792';
piCId = '63377';

(function() {
	function async_load(){
		var s = document.createElement('script'); s.type = 'text/javascript';
		s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js';
		var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);
	}
	if(window.attachEvent) { window.attachEvent('onload', async_load); }
	else { window.addEventListener('load', async_load, false); }
})();
</script>


</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>NewApp</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>


	<%= csrf_meta_tags %>

	<style>
		.navbar-brand {
			background: url(<%= getImageByCode("03") == false ? image_url('logo.png') : getImageByCode("03") %>) no-repeat left center;
			background-size: contain;
			height: 50px;
			width: 250px;
		}


	</style>



</head>
<body>

	<!-- Fixed navbar -->

<%= yield %>

</body>
</html>